const I18N={
zh:{dashboard:'概览',models:'模型管理',users:'用户管理',stats:'统计',docs:'API 文档',server:'Server',online:'Online',add_provider:'+ 新增 Provider',health:'Health',edit:'编辑',delete:'删除',set_default:'设为默认',default_badge:'★ 默认',modal_add_provider:'新增 Provider',fld_name:'名称',fld_protocol:'协议',fld_base_url:'API Base URL',fld_api_key:'API Key',btn_cancel:'取消',btn_confirm:'确认',generate_apikey:'+ 生成 API Key',th_key:'API Key',th_name:'名称',th_note:'备注',th_requests:'请求',th_input:'输入Token',th_output:'输出Token',th_cached:'Cached',th_created:'创建时间',th_last_used:'最后使用',th_actions:'操作',copy:'复制',details:'详情',collapse:'收起',not_used:'未使用',no_keys:'暂无 API Key',modal_generate_key:'生成新 API Key',fld_key_name:'名称（如：Hermes Agent）',fld_key_note:'备注（可选）',btn_generate:'生成',key_generated:'API Key 已生成',key_warning:'⚠ 此 Key 仅显示一次，请立即复制保存',btn_copied_close:'已复制，关闭',all_providers:'全部 Provider',all_models:'全部模型',last_7days:'最近7天',today:'今天',last_30days:'最近30天',all_time:'全部',total_requests:'总请求数',input_tokens:'输入 Token',output_tokens:'输出 Token',cached_tokens:'Cached Token',top5_models:'Top 5 模型请求量',th_provider:'Provider',th_model:'模型',provider_count:'Provider 数量',apikey_count:'API Key 数量',today_requests:'今日请求',recent_activity:'最近活动',llm_proxy_api:'LLM Proxy API',admin_api:'Admin API'},
en:{dashboard:'Dashboard',models:'Models',users:'API Keys',stats:'Statistics',docs:'API Docs',server:'Server',online:'Online',add_provider:'+ Add Provider',health:'Health',edit:'Edit',delete:'Delete',set_default:'Set Default',default_badge:'★ Default',modal_add_provider:'Add Provider',fld_name:'Name',fld_protocol:'Protocol',fld_base_url:'API Base URL',fld_api_key:'API Key',btn_cancel:'Cancel',btn_confirm:'Confirm',generate_apikey:'+ Generate API Key',th_key:'API Key',th_name:'Name',th_note:'Note',th_requests:'Requests',th_input:'Input Tokens',th_output:'Output Tokens',th_cached:'Cached',th_created:'Created',th_last_used:'Last Used',th_actions:'Actions',copy:'Copy',details:'Details',collapse:'Collapse',not_used:'Never',no_keys:'No API Keys',modal_generate_key:'Generate New API Key',fld_key_name:'Name (e.g. Hermes Agent)',fld_key_note:'Note (optional)',btn_generate:'Generate',key_generated:'API Key Generated',key_warning:'⚠ This key is shown only once. Copy it now.',btn_copied_close:'Copied, Close',all_providers:'All Providers',all_models:'All Models',last_7days:'Last 7 days',today:'Today',last_30days:'Last 30 days',all_time:'All time',total_requests:'Total Requests',input_tokens:'Input Tokens',output_tokens:'Output Tokens',cached_tokens:'Cached Tokens',top5_models:'Top 5 Models by Requests',th_provider:'Provider',th_model:'Model',provider_count:'Providers',apikey_count:'API Keys',today_requests:'Requests Today',recent_activity:'Recent Activity',llm_proxy_api:'LLM Proxy API',admin_api:'Admin API'},
ja:{dashboard:'ダッシュボード',models:'モデル管理',users:'ユーザー管理',stats:'統計',docs:'API ドキュメント',server:'Server',online:'Online',add_provider:'+ プロバイダー追加',health:'Health',edit:'編集',delete:'削除',set_default:'デフォルト設定',default_badge:'★ デフォルト',modal_add_provider:'プロバイダー追加',fld_name:'名称',fld_protocol:'プロトコル',fld_base_url:'API Base URL',fld_api_key:'API Key',btn_cancel:'キャンセル',btn_confirm:'確認',generate_apikey:'+ API Key 生成',th_key:'API Key',th_name:'名称',th_note:'備考',th_requests:'リクエスト',th_input:'入力Token',th_output:'出力Token',th_cached:'Cached',th_created:'作成日時',th_last_used:'最終使用',th_actions:'操作',copy:'コピー',details:'詳細',collapse:'閉じる',not_used:'未使用',no_keys:'API Key がありません',modal_generate_key:'新規 API Key 生成',fld_key_name:'名称（例：Hermes Agent）',fld_key_note:'備考（任意）',btn_generate:'生成',key_generated:'API Key が生成されました',key_warning:'⚠ この Key は一度のみ表示されます。今すぐコピーしてください。',btn_copied_close:'コピー済み、閉じる',all_providers:'すべての Provider',all_models:'すべてのモデル',last_7days:'過去7日間',today:'今日',last_30days:'過去30日間',all_time:'全期間',total_requests:'総リクエスト数',input_tokens:'入力 Token',output_tokens:'出力 Token',cached_tokens:'Cached Token',top5_models:'リクエスト数 Top 5',th_provider:'Provider',th_model:'モデル',provider_count:'プロバイダー数',apikey_count:'API Key 数',today_requests:'本日リクエスト',recent_activity:'最近のアクティビティ',llm_proxy_api:'LLM Proxy API',admin_api:'Admin API'}
};
function applyLang(l){document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n,v=I18N[l]?.[k];if(v)e.textContent=v});localStorage.setItem('ntm-lang',l);const s=document.getElementById('lang-select');if(s)s.value=l}
function openModal(id){const m=document.getElementById(id);m.classList.remove('hidden');m.classList.add('flex')}
function closeModal(id){const m=document.getElementById(id);m.classList.add('hidden');m.classList.remove('flex')}
document.addEventListener('DOMContentLoaded',()=>{const s=localStorage.getItem('ntm-lang')||'zh';applyLang(s)});
